### PR TITLE
Refactor marshalling of simulation properties to fix unit test errors

### PR DESCRIPTION
**Pull request by ghost**
@romartin 
This fixes the unit test errors with the new evaluation.bpmn process.
I think the reason this caused errors is that the previous evaluation process was created when User Tasks had simulation properties in the UI, whereas the new one was created after we removed the simulation properties. As a consequence, the new evaluation.bpmn process contains some empty simulation information.
The refactoring I've added was done recently by Jozef Marko in jbpm-designer, and it made sense to add it here. It does more checking for null values than the old code, which is why it fixes the unit test errors. Incidentaly, Jozef has done some other factoring of the marshalling classes which I'll also add to wirez.

### CODE REVIEW

**Comment by romartin** [comment]
Hi @jlindop , ah I see... so this is a fix for the Bpmn2JsonMarhsaller class, sounds good. But mm the problem here is that those classes are just a copy from the jbpm-designer ones, so doing fixes here probably it's not the best solution.

The main reason why this "legacy" package is here just a copy/paste was that I was not easily able to add jbpm-designer-backend as dependency on wirez due to some transitive dependency issues. So to move forward I just copied here the required classes. 

The best option now would be removing this "legacy·" package and its classes and try to add again the jbpm-designer-backend dependency and just use the latest marhsaller classes from that artifact. 

Is this ix is already applied to the jbpm-designer as well? If so, I will try just to then add the dependency, remove all these classes so I should have the fixed version as well, is it? Thanks!!

**Comment by romartin** [comment]
just looking now at adding again the jbpm-designer-backend dependency and trying to remove the legacy package. Will let you know...

**Comment by romartin** [comment]
hey @jlindop I'm trying to get the jbpm-designer-backend and its marshallers working here but no success yet. When adding this dependency the party starts :) It has lots of transitive dependencies and CDI complains at runtime... not easy for now. 

Do you know if should be feasible to create a lightweight jar artifact on jbpm-designer that only contains marshalling stuff? So I do not need the other stuff, such as services, servlets etc etc...

**Comment by ghost** [comment]
Hi @romartin,  I don't think it's a good idea to change jbpm-designer so that wirez can have a dependency on a module for doing marshalling. (I also agree that using adapted copies of jbpm-designer's classes isn't a great solution (-: ) Whatever we do that involves using jbpm-designer's marshalling code is not a good long-term solution to the marshalling issue in wirez, so your quick solution of making copies then adapting the classes in wirez seems a reasonable way to go. If you still want to change this to a dependency on a new jbpm-designer marshalling module, then we should discuss it with Kris.

**Comment by romartin** [comment]
Ok thanks @jlindop ! Please try to have this duplicity on your mind until we get the new marshallers, so if any bug fixes can be ported here, we should do it :)
Merged: 6b2cb67062d8d8be5f56c119dcc1876571fae22a

**Pull request closed without merging**
