### PR TITLE
Moving forms dependencies to kie-wb-common.

### PR DESCRIPTION
**Pull request by pefernan**
@romartin There are some issues on the webapp, we should take a look before merging.

### CODE REVIEW

**Comment by romartin** [comment]
Hi @pefernan ,
I have fixed some problems by adding the wb security integration and you can skip the client side error about negative CSS heights by building this PR locally ( for now, so you can move forward if you have time ) -> https://github.com/uberfire/uberfire/pull/494
Please check your PR again when possible and lemme know something! 
Thanks!

**Comment by pefernan** [comment]
@romartin fixed conflicts

**Comment by romartin** [comment]
Hi @pefernan , found deployment issues on the wildfly 10 distribution, please see here -> https://gist.github.com/romartin/c4856092d968176b69264a3fa283121a
Probably some missing bean exclusions? It seems those classes are client side... Please can you review? 
Thanks!

**Comment by romartin** [comment]
PS @pefernan : The UF docks bug has been fixed on UF master's branch.

**Comment by pefernan** [comment]
@romartin As we discussed yesterday, it was a dependency issue (client module on backend)... fixed!

**Comment by romartin** [comment]
Thanks @pefernan , it works :) 
Merged: fbf2fa68a8df63eb0525fed770709ac7740ad258

**Pull request closed without merging**
