### PR TITLE
Moved Form Modeler's Annotation processing mechanism to use DMO instead of reflection.

### PR DESCRIPTION
**Pull request by pefernan**
PLEASE DO NOT MERGE YET

### CODE REVIEW

**Comment by pefernan** [comment]
@romartin merge after this https://github.com/droolsjbpm/livespark/pull/43

**Comment by romartin** [comment]
Hi @pefernan , when merging this I'm not able to run the showcase using SDM from Intellij :( I have noticed that neither building from command line, the annotations generated code for the different designer's annotations is not being generated, so I think that's the issue. Were you able to run it in SDM? from Intellij? would be nice if you can give it a try and give me some feedback please, as not sure if it's my local...

**Comment by romartin** [comment]
Meanwhile this PR is not merged, using the latest Livespark snapshot probably brokes the build, a workaround is to checkout this concrete LS commit and run the build again -> https://github.com/droolsjbpm/livespark/commit/f430f53754f402dbed8c08b7417d0afbc6711bac

**Comment by romartin** [comment]
Hi @pefernan , tbh don't know why but today it's all working fine with no changes.... the root problem was with Maven and annotation processors, so I think that it was probably some issue on a parent or transient pom for a certain snapshot that was causing this... Anyway, it works fine for now, so merged: 435c929a8b04c89631fb688da7a56ca4fa46ba1a Thanks!

**Pull request closed without merging**
