### PR TITLE
GUVNOR-2173 - Asset Oracle: Change Impact prediction

### PR DESCRIPTION
**Pull request by mrietveld**
@romartin -- This should be merged once all of the PR's for https://github.com/droolsjbpm/kie-wb-common/pull/414 are merged. 

Let me know if you have any questions.

### CODE REVIEW

**Comment by romartin** [comment]
Okk, waiting for those PR to get merged before this one. Thanks!

**Comment by ghost** [comment]
Tested with the other PR's and looks good (builds without errors and showcase runs ok):
- https://github.com/droolsjbpm/jbpm/pull/511 (merged)
- https://github.com/uberfire/uberfire/pull/455 (merged)
- https://github.com/droolsjbpm/kie-wb-common/pull/414
- https://github.com/droolsjbpm/drools-wb/pull/257

Still waiting for the kie-wb-common and drools-wb PR's to be merged.

**Comment by mrietveld** [comment]
@jlindop Thanks -- finishing the fixes to the designer pr today.

**Comment by ghost** [comment]
Re-tested after all other PR's have been merged, and works fine.
+1

**Comment by mrietveld** [comment]
@jlindop @romartin Thanks!

**Pull request merged**
